import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | WJ Study",
  description: "Privacy Policy for WJ Study.",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-slate-950 text-slate-200 font-sans">
      <div className="mx-auto max-w-3xl px-5 py-10">
        <Link
          href="/"
          className="inline-block mb-8 text-sm font-medium text-blue-400 hover:underline"
        >
          ← Back to Home
        </Link>

        <article className="prose prose-invert prose-slate max-w-none prose-headings:font-bold prose-a:text-blue-400">
          <h1>Privacy Policy</h1>
          <p className="text-sm text-slate-400">Last updated: September 24, 2026</p>

          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and
            disclosure of Your information when You use the Service and tells You about Your
            privacy rights and how the law protects You.
          </p>
          <p>
            We use Your Personal Data to provide and improve the Service. We collect, use, and
            disclose Your information as described in this Privacy Policy and, where required by
            applicable law, only where We have a valid legal basis to do so, including Your consent
            (where consent is required).
          </p>

          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            The words whose initial letters are capitalized have meanings defined under the
            following conditions. The following definitions shall have the same meaning regardless
            of whether they appear in singular or in plural.
          </p>

          <h3>Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          <ul>
            <li><strong>Account</strong> means a unique account created for You to access Our Service or parts of Our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where &quot;control&quot; means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Application</strong> refers to WJ Study, the software program provided by the Company.</li>
            <li><strong>Company</strong> (referred to as either &quot;the Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in this Privacy Policy) refers to WJ Study.</li>
            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website, among its many uses.</li>
            <li><strong>Country/State</strong> refers to: Vietnam.</li>
            <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> (or &quot;Personal Information&quot;) is any information that relates to an identified or identifiable individual. We use &quot;Personal Data&quot; and &quot;Personal Information&quot; interchangeably unless a law uses a specific term.</li>
            <li><strong>Service</strong> refers to the Application or the Website or both.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>User</strong> means any individual who accesses or uses the Service.</li>
            <li><strong>Website</strong> refers to WJ Study.</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>

          <h2>Collecting and Using Your Personal Information</h2>
          <h3>Types of Data Collected</h3>
          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain personally
            identifiable information that can be used to contact or identify You. Personally
            identifiable information may include, but is not limited to:
          </p>
          <ul>
            <li>Email address</li>
          </ul>

          <h4>Usage Data</h4>
          <p>Usage Data is collected automatically when using the Service.</p>
          <p>
            Usage Data may include information such as Your Device&apos;s Internet Protocol address
            (e.g. IP address), browser type, browser version, the pages of Our Service that You
            visit, the time and date of Your visit, the time spent on those pages, unique device
            identifiers and other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain
            information automatically, including, but not limited to, the type of mobile device You
            use, Your mobile device&apos;s unique ID, the IP address of Your mobile device, Your
            mobile operating system, the type of mobile Internet browser You use, unique device
            identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that Your browser sends whenever You visit Our Service
            or when You access the Service by or through a mobile device.
          </p>

          <h4>Tracking Technologies and Cookies</h4>
          <p>
            We use tracking technologies (such as cookies) to track the activity and to improve Our
            Service. The technologies We use may include:
          </p>
          <ul>
            <li>
              <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your
              Device. You can instruct Your browser to refuse all Cookies or to indicate when a
              Cookie is being sent. However, if You do not accept Cookies, You may not be able to
              use some parts of Our Service.
            </li>
            <li>
              <strong>Web Beacons.</strong> Certain sections of Our Service may contain small
              electronic files known as web beacons that permit the Company, for example, to count
              users who have visited those pages and for other related website statistics.
            </li>
          </ul>
          <p>
            Cookies can be &quot;Persistent&quot; or &quot;Session&quot; Cookies. Persistent Cookies
            remain on Your personal computer or mobile device when You go offline, while Session
            Cookies are deleted as soon as You close Your web browser.
          </p>
          <p>
            Where required by law, We use non-essential cookies only with Your consent. You can
            withdraw or change Your consent at any time using Our cookie preferences tool (if
            available) or through Your browser/device settings.
          </p>
          <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
          <ul>
            <li>
              <strong>Necessary / Essential Cookies</strong> — Type: Session Cookies. Administered
              by: Us. Purpose: essential to provide You with services available through the Website
              and to enable You to use some of its features, including authenticating users and
              preventing fraudulent use of accounts.
            </li>
            <li>
              <strong>Cookies Policy / Notice Acceptance Cookies</strong> — Type: Persistent
              Cookies. Administered by: Us. Purpose: identify whether users have accepted the use of
              cookies on the Website and record consent choices for future visits.
            </li>
            <li>
              <strong>Functionality Cookies</strong> — Type: Persistent Cookies. Administered by:
              Us. Purpose: remember choices You make when You use the Website, such as login
              details or language preference, for a more personal experience.
            </li>
          </ul>

          <h3>Use of Your Personal Data</h3>
          <p>The Company may use Personal Data for the following purposes:</p>
          <ul>
            <li><strong>To provide and maintain Our Service</strong>, including to monitor the usage of Our Service.</li>
            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased, or of any other contract with Us through the Service.</li>
            <li><strong>To contact You:</strong> by email, telephone, SMS, or other equivalent forms of electronic communication regarding updates or informative communications, including security updates, when necessary or reasonable.</li>
            <li><strong>To provide You</strong> with news, special offers, and general information about other goods, services and events, where permitted by applicable law. You may opt out at any time.</li>
            <li><strong>To manage Your requests:</strong> to attend and manage Your requests to Us.</li>
            <li><strong>For business transfers:</strong> to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
            <li><strong>For other purposes:</strong> data analysis, identifying usage trends, and evaluating and improving Our Service.</li>
          </ul>
          <p>We may share Your Personal Data in the following situations:</p>
          <ul>
            <li><strong>With Service Providers</strong> to monitor and analyze the use of Our Service, and to contact You.</li>
            <li><strong>For business transfers</strong> in connection with a merger, sale of Company assets, financing, or acquisition.</li>
            <li><strong>With Affiliates</strong>, who will be required to honor this Privacy Policy.</li>
            <li><strong>With other users</strong>, if Our Service offers public areas.</li>
            <li><strong>With Your consent</strong>, for any other disclosed purpose.</li>
          </ul>

          <h4>Text Messages Privacy Notice</h4>
          <p>
            You have the option to receive text (SMS) messages from Us. If You opt in, We will
            collect and store information such as Your phone number, the date and method of Your
            consent, and message delivery and read information.
          </p>
          <p>
            No mobile information will be shared with or sold to third parties or affiliates for
            marketing or promotional purposes. Consent to receive text messages is not a condition
            of any purchase or use of Our Service. If You consent, You agree to receive messages
            related to customer care, account notifications, delivery updates, authentication codes,
            security alerts, and marketing offers.
          </p>
          <p>
            Reply STOP to opt out. Reply HELP for support. Message &amp; data rates may apply.
            Messaging frequency may vary. Carriers are not liable for delayed or undelivered
            messages.
          </p>

          <h3>Retention of Your Personal Data</h3>
          <p>
            The Company will retain Your Personal Data only for as long as is necessary for the
            purposes set out in this Privacy Policy, and to comply with legal obligations, resolve
            disputes, and enforce Our agreements and policies.
          </p>
          <p>Typical retention periods (as maximums, often shorter in practice):</p>
          <ul>
            <li>User accounts: for the duration of the Account plus up to 24 months after closure.</li>
            <li>Support tickets and chat transcripts: up to 24 months.</li>
            <li>Website analytics, application usage statistics, and server logs: up to 24 months.</li>
          </ul>
          <p>
            We may retain data longer where required by law, for legal claims, at Your request, or
            due to technical backup limitations. You may request information about retention by
            contacting Us.
          </p>

          <h3>Transfer of Your Personal Data</h3>
          <p>
            Your information, including Personal Data, is processed at the Company&apos;s operating
            offices and in any other places where the parties involved in the processing are
            located, which may include jurisdictions with different data protection laws than Your
            own. Where required, We ensure appropriate safeguards are in place for such transfers.
          </p>

          <h3>Delete Your Personal Data</h3>
          <p>
            You have the right to delete or request that We assist in deleting the Personal Data
            that We have collected about You. You may update, amend, or delete Your information at
            any time via Your account settings, or by contacting Us. We may need to retain certain
            information where We have a legal obligation to do so.
          </p>

          <h3>Disclosure of Your Personal Data</h3>
          <p>
            <strong>Business Transactions:</strong> if the Company is involved in a merger,
            acquisition or asset sale, Your Personal Data may be transferred; We will provide notice
            beforehand.
          </p>
          <p>
            <strong>Law Enforcement:</strong> the Company may disclose Your Personal Data if
            required by law or in response to valid requests by public authorities.
          </p>
          <p>
            <strong>Other Legal Requirements:</strong> the Company may disclose Your Personal Data
            in the good-faith belief that doing so is necessary to comply with a legal obligation,
            protect the rights or property of the Company, prevent or investigate wrongdoing,
            protect the safety of Users, or protect against legal liability.
          </p>

          <h3>Security of Your Personal Data</h3>
          <p>
            The security of Your Personal Data is important to Us, but no method of transmission
            over the Internet or method of electronic storage is 100% secure. While We strive to use
            commercially reasonable means to protect Your Personal Data, We cannot guarantee its
            absolute security.
          </p>

          <h2>Children&apos;s and Minors&apos; Privacy</h2>
          <p>
            The Service is not directed to, and We do not knowingly collect Personal Information
            from, anyone under the age of 16. If You are a parent or guardian and believe Your child
            has provided Us with Personal Information, please contact Us so We can remove it.
          </p>

          <h2>Links to Other Websites</h2>
          <p>
            Our Service may contain links to other websites not operated by Us. We strongly advise
            You to review the Privacy Policy of every site You visit. We have no control over and
            assume no responsibility for the content or privacy practices of any third-party sites.
          </p>

          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You by posting the
            new Privacy Policy on this page and updating the &quot;Last updated&quot; date above.
          </p>

          <h2>Contact Us</h2>
          <p>If You have any questions about this Privacy Policy, You can contact Us by email.</p>
        </article>
      </div>
    </div>
  );
}

